In [1]:
def distance(x):
    import numpy as np
    lst = np.zeros((5,5))
    res = []
    new = []
    pos=[]
    neg=[]
    for i in range(5):
        for j in range(5):
            y=i*5+j+1
            if x[i][j]=="R":
                res.append((i)*5+(j+1))
            for k in range(5):
                for l in range(5):
                    
                    if x[k][l]=="F":
                        f= (k*5+l+1)

    for t in res:
        a= t-f
        if a>=0:
            pos.append(a)
        else:
            neg.append(a)
    pos.sort()
    n = np.sort(neg)[::-1]
    if len(n)>0 and len(pos)>0:
        new = [n[0], pos[0]]
    elif len(n)==0 and len(pos)>0:
        new= [pos[0]]
    elif len(n)>0 and len(pos)==0:
        new=[n[0]]
    np.sort(new)
    if len(new)>1:
        v=new[0]+1
        w=new[1]-1
    elif new[0]>0:
        v=-f+1
        w=new[0]
    elif new[0]<0:
        v=new[0]+1
        w=5*5-f
    

    for k in range(5):
        for l in range(5):
            if x[k][l]=="F":
  
                for z in range(v,w+1):
                    p = int((k*5+l+z)/5)
                    q= int((k*5+l+z)%5)
                    lst[p][q]=abs(z)

                    
 
 

                        
    print(lst)
                

In [2]:
distance([["","","","",""],["","","R","R",""],["","","F","",""],["","","","R",""],["","","","",""]])

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3.]
 [2. 1. 0. 1. 2.]
 [3. 4. 5. 0. 0.]
 [0. 0. 0. 0. 0.]]
